#!/bin/sh -ex

DB_NAME=ezplatform
DB_USER=ezplatform
DB_PASS=$(mcookie)

WEBROOT=/var/www/ezplatform

# tweak apache-credit
CONF=/etc/apache2/mods-available/substitute.conf
sed -i "s|</body>|</footer>|g" $CONF

cd $WEBROOT

# php.ini tweaks
PHPINI=/etc/php/8.2/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 256M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"America/Los_Angeles\"|" $PHPINI
sed -i "s|^memory_limit.*|memory_limit = 1G|" /etc/php/8.2/cli/php.ini

# configure apache
a2dissite 000-default
a2ensite ezplatform
a2enmod rewrite

# start services
service mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS';"

ENVFILE=/var/www/ezplatform/.env

echo "DATABASE_DRIVER=\"pdo_mysql\"" >> $ENVFILE
sed -i "s|APP_ENV=dev|APP_ENV=prod|" $ENVFILE
sed -i "s|DATABASE_URL=\"postgres.*\"||" $ENVFILE
sed -i "s|# DATABASE_URL=\"mysql:\/\/.*\"|DATABASE_URL=\"mysql://$DB_USER:$DB_PASS@localhost:3306/$DB_NAME?serverVersion=15\"|" $ENVFILE

COMPOSER_MEMORY_LIMIT=-1 composer install --no-dev --no-interaction

php bin/console ibexa:install
php bin/console ibexa:graphql:generate-schema

composer run-script post-install-cmd --no-dev --no-interaction

chown -R www-data:www-data $WEBROOT/var

sed -i "s|^memory_limit.*|memory_limit = 256M|" /etc/php/8.2/cli/php.ini

# stop services
service mysql stop

