#!/bin/bash -e

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF="/var/www/ezplatform/.env"
sed -i "s|APP_SECRET=.*|APP_SECRET=$PASSWORD|" $CONF
sed -i "s|DATABASE_URL=\"mysql:\/\/ezplatform:.*\"|DATABASE_URL=\"mysql:\/\/ezplatform:$PASSWORD@localhost:3306/ezplatform?appVersion=15\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=ezplatform --pass="$PASSWORD"

